# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17lf5DHmynsJd5v4X-pvREusACztxar3k
"""

!pip install ultralytics

import cv2
import numpy as np
import matplotlib.pyplot as plt
from ultralytics import YOLO
import os
from google.colab import files # Import files module for Colab uploads

# ------------------------------------------------
# Load YOLO Model
# ------------------------------------------------
print("🔄 Loading YOLO model...")
model = YOLO("yolo11l.pt")

# ------------------------------------------------
# Input Image Path (Modified for Colab file upload)
# ------------------------------------------------
print("📂 Please upload your image file(s) for analysis.")
uploaded = files.upload() # This will open a file selection dialog in Colab

image_path = None
if uploaded:
    # Assuming only one image file is to be processed at a time
    image_path = list(uploaded.keys())[0] # Get the name of the first uploaded file
    print(f"✅ Image '{image_path}' uploaded successfully.")
else:
    # If no file is uploaded, raise an error to stop execution
    raise FileNotFoundError("❌ No image file was uploaded. Please upload an image to proceed.")

# The original check for os.path.exists is no longer strictly needed here after files.upload()
# but serves as an additional safeguard.
if not os.path.exists(image_path):
    raise FileNotFoundError(f"❌ Uploaded image not found on disk: {image_path}")

# ------------------------------------------------
# Read Image
# ------------------------------------------------
image = cv2.imread(image_path)

if image is None:
    raise ValueError("❌ Unable to read image. It might be corrupted or not a valid image format.")

# ------------------------------------------------
# Upscale Image
# Helps detect small/far vehicles
# ------------------------------------------------
image = cv2.resize(
    image,
    None,
    fx=2,
    fy=2,
    interpolation=cv2.INTER_CUBIC
)

# ------------------------------------------------
# Run Detection
# ------------------------------------------------
print("🚦 Analyzing traffic image...")

results = model.predict(
    source=image,
    imgsz=1280,
    conf=0.20,
    iou=0.45,
    verbose=False
)

result = results[0]

# ------------------------------------------------
# Vehicle Classes (COCO)
# ------------------------------------------------
vehicle_classes = [1, 2, 3, 5, 7]

vehicle_names = {
    1: "Bicycle",
    2: "Car",
    3: "Motorcycle",
    5: "Bus",
    7: "Truck"
}

vehicle_count = {
    "Bicycle": 0,
    "Car": 0,
    "Motorcycle": 0,
    "Bus": 0,
    "Truck": 0
}

num_vehicles_detected = 0

# ------------------------------------------------
# Count Vehicles
# ------------------------------------------------
for box in result.boxes:
    cls = int(box.cls[0])
    conf = float(box.conf[0])

    if cls in vehicle_classes and conf >= 0.20:
        num_vehicles_detected += 1
        vehicle_count[vehicle_names[cls]] += 1

# ------------------------------------------------
# Traffic Density Logic
# ------------------------------------------------
if num_vehicles_detected > 30:
    traffic_status = "HEAVY TRAFFIC"
    light_color = "RED"
    green_time = 10
    red_time = 30

elif num_vehicles_detected > 15:
    traffic_status = "MODERATE TRAFFIC"
    light_color = "YELLOW"
    green_time = 20
    red_time = 20

else:
    traffic_status = "LIGHT TRAFFIC"
    light_color = "GREEN"
    green_time = 30
    red_time = 10

# ------------------------------------------------
# Draw Results
# ------------------------------------------------
annotated = result.plot()

cv2.putText(
    annotated,
    f"Vehicles: {num_vehicles_detected}",
    (20, 40),
    cv2.FONT_HERSHEY_SIMPLEX,
    1,
    (0, 255, 0),
    3
)

cv2.putText(
    annotated,
    traffic_status,
    (20, 90),
    cv2.FONT_HERSHEY_SIMPLEX,
    1,
    (0, 255, 255),
    3
)

# ------------------------------------------------
# Convert Image for Display
# ------------------------------------------------
display_image = cv2.cvtColor(
    annotated,
    cv2.COLOR_BGR2RGB
)

# ------------------------------------------------
# Display Result
# ------------------------------------------------
plt.figure(figsize=(14, 10))
plt.imshow(display_image)
plt.title("AI Traffic Congestion Detection")
plt.axis("off")
plt.show()

# ------------------------------------------------
# Save Result
# ------------------------------------------------
output_file = "traffic_analysis_result.jpg"

cv2.imwrite(
    output_file,
    cv2.cvtColor(display_image, cv2.COLOR_RGB2BGR)
)

# ------------------------------------------------
# Print Report
# ------------------------------------------------
print("\n==============================")
print("🚦 TRAFFIC ANALYSIS REPORT")
print("==============================")
print(f"Total Vehicles Detected : {num_vehicles_detected}")
print(f"Traffic Status          : {traffic_status}")
print(f"Traffic Light           : {light_color}")
print(f"Suggested Green Time    : {green_time} sec")
print(f"Suggested Red Time      : {red_time} sec")
print("==============================")

print("\n📊 Vehicle Breakdown:")
for vehicle, count in vehicle_count.items():
    print(f"{vehicle}: {count}")

print(f"\n📁 Result saved as: {output_file}")
print("\n✅ Analysis Complete!")